{{- if eq .Values.enablessh true -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ssh
  labels:
    app: {{ .Release.Name }}
  annotations:
    purelb.io/service-group: privmuni
    external-dns.alpha.kubernetes.io/hostname: {{ include "dns.name" . }}
    metallb.universe.tf/address-pool: privmuni
spec:
  type: LoadBalancer
  allocateLoadBalancerNodePorts: false
  ports:
  - port: 2222
    name: ssh
    targetPort: 2222
  selector:
    app: {{ .Release.Name }}
  externalTrafficPolicy: Local
{{- end -}}
