apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dataspecer.fullname" . }}-config
  labels:
    {{- include "dataspecer.labels" . | nindent 4 }}
data:
  BASE_URL: "https://{{ .Values.host }}.{{ .Release.Namespace }}.dyn.cloud.e-infra.cz"
  PORT: "{{ .Values.service.port }}"
  DOCKER: "1"
  STATIC_FILES_PATH: "/usr/src/app/html/"
