apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dataspecer.fullname" . }}-auth
  labels:
    {{- include "dataspecer.labels" . | nindent 4 }}
type: Opaque
stringData:
  users: {{ htpasswd (required "basicAuth.user is required" .Values.basicAuth.user) (required "basicAuth.password is required" .Values.basicAuth.password) | quote }}
