apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  clusterIP: None
  ports:
  - port: 8787
    targetPort: 8787
  selector:
    app: {{ .Release.Name }}
{{- if eq .Values.ssh.enable true }}
{{- if ne .Values.ssh.key "" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: sshkey-{{ .Release.Name }}
type: Opaque
data:
   key: {{ .Values.ssh.key | b64enc }}
{{- end }}
{{- end }}
