desktop: "cerit.io/ansys-desktop:2019R3"
mincpu: 1
maxcpu: 4
minram: 4096Mi
maxram: 16384Mi
defhostname: true
customhostname: ""
username: ""
password: ""
persistenthome: true
resolution: "1920x1080"
