{{- if eq .Values.ssh.enable true -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ssh
  labels:
    app: {{ .Release.Name }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: ssh-{{ include "dns.name" . }}
spec:
  type: LoadBalancer
  allocateLoadBalancerNodePorts: false
  ports:
  - port: 2222
    name: ssh
    targetPort: 2222
  selector:
    app: {{ .Release.Name }}
  externalTrafficPolicy: Local
{{- end -}}
