apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  clusterIP: None
  ports:
  - port: 7474
    targetPort: 7474
    name: web
  - port: 7687
    targetPort: 7687
    name: bolt
  selector:
    app: {{ .Release.Name }}
