apiVersion: apps/v1
kind: Deployment
metadata:
  name: rstudio-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rstudio-server
  template:
    metadata:
      labels:
        app: rstudio-server
    spec:
      containers:
      - name: rstudio-server
        image: cerit.io/rstudio:v0.1
        env:
        - name: PASSWORD
          valueFrom:
           secretKeyRef:
             key: password
             name: rstudiopassword
        securityContext:                                                          
          runAsUser: 1000 
          runAsGroup: 1000
        ports:
        - containerPort: 8787
        resources:
          limits:
            cpu: {{ .Values.maxcpu }}
            memory: {{ .Values.maxram }}
          requests:
            cpu: {{ .Values.mincpu }}
            memory: {{ .Values.minram }}
{{- if ne .Values.storage "" }}
        volumeMounts:
        - name: data
          mountPath: /home/rstudio 
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: pvc-rstudio-{{ .Values.storage | regexFind "^[^/]*" | replace "." "-" }}
{{ end }}
