apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  annotations:
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-body-size: 6000m
    nginx.org/client-max-body-size: 6000m
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ include "dns.name" . }}
      secretName: {{ include "secret.name" . }}
  rules:
  - host: {{ include "dns.name" . }}
    http:
      paths:
      - backend:
          service: 
            name: {{ .Release.Name }}
            port:
              number: 80
        pathType: ImplementationSpecific
