{{- if ne .Values.extrstorage false }}
{{- if eq .Values.storage "" }}
{{- fail "You enabled external storage but did not select storage server such as brno12-cerit. Please, delete application and start again with correctly filled form." }}
{{- end }}
{{- if ne .Values.storage "" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Release.Namespace }}-{{ .Values.storage | regexFind "^[^/]*" | replace "." "-" }}
  labels:
    cerit-cifs-secret: "yes"
    storage: {{ .Values.storage | regexFind "^[^/]*" }}
    share: {{ .Values.storage | regexFind "[^/]*$"  }}
data:
  mount_flags: {{ printf "username=%s,password=%s,uid=1000,gid=1000,nosetuids,vers=3.11,noserverino" .Values.storageusername .Values.storagepassword | b64enc | quote }}
type: Opaque
{{- end }}
{{- end }}
