{{- if ne .Values.storage.internal.usepvc true }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-{{ .Release.Namespace }}-{{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: "nfs-csi"
{{- end }}
