apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Release.Namespace }}-{{ .Release.Name }}.dyn.cloud.e-infra.cz
{{- if .Values.netmuni }}
    metallb.io/address-pool: privmuni
{{- end }}
spec:
  type: LoadBalancer
  allocateLoadBalancerNodePorts: false
  ports:
  - port: 5901
    targetPort: 5901
  selector:
    app: {{ .Release.Name }}
  externalTrafficPolicy: Local
