desktop: "cerit.io/desktops/blender:4.2.3"
mincpu: 1
maxcpu: 4
minram: 4096Mi
maxram: 16384Mi
defhostname: true
customhostname: ""
username: ""
password: ""
persistenthome: true
resolution: "1920x1080"
gpu: Part
