apiVersion: v1
data:
  password: {{ .Values.db.password | b64enc | quote }}
  username: {{ .Values.db.owner | b64enc | quote }}
kind: Secret
metadata:
  name: {{ .Values.db.name }}-db-app
type: kubernetes.io/basic-auth
