{{- if .Values.db.backup.enable }}
apiVersion: v1
data:
  ACCESS_KEY_ID: {{ .Values.db.backup.accesskey | b64enc | quote }}
  ACCESS_SECRET_KEY: {{ .Values.db.backup.secretkey | b64enc | quote }}
kind: Secret
metadata:
  name: {{ .Release.Name }}-s3-creds
type: Opaque
{{- end }}
