apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/components-cm.yaml") . | sha256sum }}
    spec:
      securityContext:
        fsGroupChangePolicy: OnRootMismatch
        fsGroup: 1000
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - name: data-pvc
          persistentVolumeClaim:
            claimName: pvc-{{ .Release.Name }}-data
{{- $filesByDir := (include "langflow.filesByDir" . | fromYaml) }}
{{- range $dir, $_ := $filesByDir }}
        - name: {{ $dir }}-config
          configMap:
            name: {{ $.Release.Name }}-{{ $dir }}-config
{{- end }}
      initContainers:
        - name: wait-for-db
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z {{ .Values.db.name }}-rw 5432; do echo "Waiting for DB..."; sleep 2; done']
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 50m
              memory: 32Mi
          securityContext:
            runAsUser: 1000
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
      containers:
        - name: langflow
          image: {{ .Values.image }}:{{ .Chart.AppVersion }}
          env:
          - name: LANGFLOW_CONFIG_DIR
            value: /app/data/langflow-cfg
          - name: LANGFLOW_COMPONENTS_PATH
            value: /components
          - name: LANGFLOW_DATABASE_URL
            value: postgresql://{{ .Values.db.owner }}:{{ .Values.db.password }}@{{ .Values.db.name }}-rw:5432/{{ .Values.db.name }}
          - name: LANGFLOW_DATABASE_CONNECTION_RETRY
            value: 'true'
          - name: LANGFLOW_HOST
            value: '0.0.0.0'
          - name: LANGFLOW_PORT
            value: '7860'
          - name: LANGFLOW_OPEN_BROWSER
            value: 'false'
          - name: LANGFLOW_CACHE_TYPE
            value: 'redis'
          - name: LANGFLOW_REDIS_HOST
            value: {{ .Release.Name }}-dragonfly
          - name: LANGFLOW_AUTO_LOGIN
            value: 'false'
          - name: DO_NOT_TRACK
            value: 'true'
          - name: LANGFLOW_SUPERUSER
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-credentials
                key: user
          - name: LANGFLOW_SUPERUSER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-credentials
                key: password
          securityContext:
            runAsUser: 1000
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 2
              memory: 4Gi
          startupProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 7860
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 10
          volumeMounts:
            - mountPath: /app/data
              name: data-pvc
{{- $filesByDir := (include "langflow.filesByDir" . | fromYaml) }}
{{- range $dir, $_ := $filesByDir }}
            - name: {{ $dir }}-config
              mountPath: /components/{{ $dir }}
{{- end }}
