{{- $hostTemplate := printf "%s-%s.dyn.cloud.e-infra.cz" .Release.Name .Release.Namespace }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  annotations:
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-body-size: 16000m
    nginx.org/client-max-body-size: 16000m
    nginx.ingress.kubernetes.io/custom-http-errors: "599"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
{{- if ne .Values.host "" }}
        - {{ .Values.host }}
{{- else }}
        - {{ $hostTemplate }}
{{- end }}
{{- if ne .Values.host "" }}
      secretName: {{ .Values.host | replace "." "-" }}-tls
{{- else }}
      secretName: {{ $hostTemplate | replace "." "-" }}-tls
{{- end }}      
  rules:
{{- if ne .Values.host "" }}
    - host: {{ .Values.host }}
{{- else }}
    - host: {{ $hostTemplate }}
{{- end }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}
                port:
                  number: 7860
