apiVersion: v1
name: desktop
annotations:
  catalog.cattle.io/release-name: desktop
version: 0.3
appVersion: 0.3
description: GPU-accelerated streaming using WebRTC or non-accelerated using VNC
icon: file://logo.png
keywords:
- Remote desktop
- Webrtc
- 3D Acceleration
- applications
- VNC
home: https://cerit.io
sources:
- https://github.com/CERIT-SC/rancher-apps
maintainers:
- name: CERIT-SC
  email: root@cerit-sc.cz
engine: gotpl
