image: langflowai/langflow
host: ''
user: 'admin'
password: ''
installChroma: true
db:
  instances: 1
  name: langflow
  owner: langflow
  password: langflow
  version: '16.8'
  resources:
    requests:
      cpu: 100m
      memory: "4096Mi"
    limits:
      cpu: 1
      memory: "4096Mi"
  storage:
    size: 10Gi
    storageClass: zfs-csi
  backup:
    enable: false
dragonfly:
  replicas: 1
  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 100m
      memory: 256Mi
  storageClass: zfs-csi
  storageLimit: 5Gi
  userId: 999
chromadb:
  chromadb:
    dataVolumeSize: "100Gi"
    dataVolumeStorageClass: zfs-csi
    auth:
      enabled: false
  podSpec:
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      fsGroup: 2000
      seccompProfile:
        type: RuntimeDefault
    containerSecurityContext:
      readOnlyRootFilesystem: false
      capabilities:
        drop:
        - ALL
      allowPrivilegeEscalation: false
