{{- if ne .Values.sshkey "" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: sshkey-{{ .Release.Name }}
type: Opaque
data:
   authorized_keys: {{ printf "%s\n" .Values.sshkey | b64enc }}
{{- end }}
