apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  annotations:
    kubernetes.io/ingress.class: nginx
    external-dns.alpha.kubernetes.io/target: {{ .Values.dnstarget }}
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts: 
        - {{ .Release.Name }}-{{ .Release.Namespace }}.dyn.cerit-sc.cz 
      secretName: {{ printf "%s-%s-dyn-cerit-sc-cz-tls" .Release.Name .Release.Namespace  }}
  rules:
  - host: {{ .Release.Name }}-{{ .Release.Namespace }}.dyn.cerit-sc.cz
    http:
      paths:
      - path: "/"
        backend:
          service: 
            name: {{ .Release.Name }}
            port:
              number: 8443
        pathType: Prefix
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: s3-{{ .Release.Name }}
  annotations:
    kubernetes.io/ingress.class: nginx
    external-dns.alpha.kubernetes.io/target: {{ .Values.dnstarget }}
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts: 
        - s3-{{ .Release.Name }}-{{ .Release.Namespace }}.dyn.cerit-sc.cz 
      secretName: {{ printf "s3-%s-%s-dyn-cerit-sc-cz-tls" .Release.Name .Release.Namespace  }}
  rules:
  - host: s3-{{ .Release.Name }}-{{ .Release.Namespace }}.dyn.cerit-sc.cz
    http:
      paths:
      - path: "/"
        backend:
          service: 
            name: {{ .Release.Name }}
            port:
              number: 9000
        pathType: Prefix
