apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
type: Opaque
data: 
   password: {{ .Values.rstudiopassword | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: terminal-{{ .Release.Name }}
type: Opaque
data:
   auth: {{ htpasswd .Values.username .Values.rstudiopassword | b64enc }}
