{{- if ne .Values.password "" -}}
apiVersion: v1
kind: Secret
metadata:
  name: terminal-{{ .Release.Name }}
type: Opaque
data:
   auth: {{ .Values.password | b64enc }}
---
{{- end }}
{{- if .Values.storage.elixir.enable }}
{{- if and (ne (toString .Values.storage.elixir.username) "") (ne .Values.storage.elixir.password "") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-storage-elixir1-cerit-sc-cz
  labels:
    cerit-cifs-secret: "yes"
  annotations:
    cerit.io/storage: "storage-elixir1.cerit-sc.cz"
    cerit.io/share: "lamb"
data:
  mount_flags: {{ printf "username=%s,password=%s,uid=1000,gid=1000,nosetuids,vers=3.11,noserverino,domain=UCN" (toString .Values.storage.elixir.username) .Values.storage.elixir.password | b64enc | quote }}
type: Opaque
{{- end }}
{{- end }}
{{- if ne .Values.sshkey "" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: sshkey-{{ .Release.Name }}
type: Opaque
data:
   key: {{ .Values.sshkey | b64enc }}
{{- end }}
