{{- if ne .Values.password "" -}}
apiVersion: v1
kind: Secret
metadata:
  name: terminal-{{ .Release.Name }}
type: Opaque
data:
   auth: {{ .Values.password | b64enc }}
---
{{- end }}
{{- if ne .Values.sshkey "" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: sshkey-{{ .Release.Name }}
type: Opaque
data:
   key: {{ .Values.sshkey | b64enc }}
{{- end }}
