apiVersion: v1
kind: Service
metadata:
  name: rstudio-server
  labels:
    app: rstudio-server
spec:
  clusterIP: None
  ports:
  - port: 8787
    targetPort: 8787
  selector:
    app: rstudio-server
