apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-netrc
type: Opaque
data: 
   .netrc: {{ printf "machine %s\nlogin \"%s\"\npassword \"%s\"\n" ( regexReplaceAll "^.*://([^/]*).*$" .Values.server "${1}" )  .Values.username .Values.password | b64enc |  quote }}
