apiVersion: v1
name: ansys
version: 2020
appVersion: 2020R1
description: ANSYS 2020R1
icon: file://logo.jpg
keywords:
- Remote desktop
- Ansys 2020R1
- Webrtc
- 3D Acceleration
- VNC
home: https://cerit.io
sources:
- https://github.com/CERIT-SC/rancher-apps
maintainers:
- name: CERIT-SC
  email: root@cerit-sc.cz
engine: gotpl
