apiVersion: apps/v1
kind: Deployment
metadata:
  name: rstudio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rstudio
  template:
    metadata:
      labels:
        app: rstudio
    spec:
      containers:
      - name: rstudio
        image: cerit/rstudio:v0.1
        env:
        - name: PASSWORD
          valueFrom:
           secretKeyRef:
             key: password
             name: rstudiopassword
        securityContext:                                                          
          runAsUser: 1000 
          runAsGroup: 1000
        ports:
        - containerPort: 8787
        resources:
          limits:
            cpu: {{ .Values.maxcpu }}
            memory: {{ .Values.maxram }}
          requests:
            cpu: {{ .Values.mincpu }}
            memory: {{ .Values.minram }}

