{{- if ne .Values.storageusername "" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-storage-{{ printf "%s" .Values.storageserver | replace "," "-" }}
  labels:
    cerit-cifs-secret: "yes"
  annotations:
    cerit.io/storage: {{ .Values.storageserver }}
    cerit.io/share: {{ .Values.storage.path }}
type: Opaque
data:
  mount_flags: {{ printf "username=%s,password=%s,uid=1000,gid=1000,nosetuids,vers=3.11,noserverino,domain=UCN" (toString .Values.storageusername) .Values.storagepassword | b64enc | quote }}
{{- end }}
