apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ include "dns.name" . }}
spec:
  type: LoadBalancer
  ports:
  - port: 11111
    targetPort: 11111
    name: data
{{- if .Values.access.ssh.enable }}
  - port: 22
    targetPort: 2222
    name: ssh
{{- end }}
  selector:
    app: {{ .Release.Name }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}
spec:
  serviceName: {{ .Release.Name  }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Release.Name }}-dataserver
        image: {{ .Values.image }}
        imagePullPolicy: Always
        args:
        - --no-mpi
        env:
        - name: NVIDIA_DRIVER_CAPABILITIES
          value: all
        - name: SSH_KEY
          value: {{ .Values.access.ssh.key | quote }}
        securityContext:                                                          
          runAsUser: 1000 
          runAsGroup: 1000
        resources:
          requests:
            cpu:  {{ .Values.resources.cpu.min }}
            memory: {{ .Values.resources.memory.min }}
          limits:
            cpu: {{ .Values.resources.cpu.max }}
            memory: {{ .Values.resources.memory.max }}
{{- if ne .Values.resources.gpu "0" }}
            nvidia.com/gpu: {{ .Values.resources.gpu }}
{{- end }}
        ports:
        - containerPort: 11111
          name: data
{{- if .Values.access.ssh.enable }}
        - containerPort: 2222
          name: ssh
{{- end }}
        volumeMounts:
        - name: dshm
          mountPath: /dev/shm
{{- if .Values.storage.persistenthome }}
        - name: home
          mountPath: /home/paraview
{{- end }}
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: 1Gi
{{- if .Values.storage.persistenthome }}
  volumeClaimTemplates:
  - metadata:
      name: home
    spec:
      accessModes: [ "ReadWriteMany" ]
      storageClassName: "nfs-csi"
      resources:
        requests:
          storage: 1Gi
{{- end }}
