image: "R 3.6.3/Debian 10"
rstudiopassword: ""
mincpu: 1
maxcpu: 4
minram: 4096Mi
maxram: 16384Mi
storage:
  enable: false
  server: ""
  username: ""
  password: ""
  persistenthome: true
  persistentopt: false
  externalpvc:
    enable: false
    name: ""
ingress:
  whitelistip: ""
networkpolicy: false
ssh:
  enable: false
  key: ""
