image: "cerit.io/ceitec/bioda"
mincpu: 1
maxcpu: 4
minram: 4096Mi
maxram: 16384Mi
sshkey: ""

storage:
  pvc1:
    enable: false
    claim: ""
  pvc2:
    enable: false
    claim: ""
  optpvc: 
    enable: true
    name: pvc-sw 

