apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  annotations:
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  tls:
   - hosts:
       - {{ printf "%s-%s.dyn.cloud.e-infra.cz" .Values.hostname .Release.Namespace }}
     secretName: {{ printf "%s-%s.dyn.cloud.e-infra.cz" .Values.hostname .Release.Namespace | replace "." "-" }}-tls 
  rules:
  - host: {{ printf "%s-%s.dyn.cloud.e-infra.cz" .Values.hostname .Release.Namespace }}
    http:
      paths:
        - path: "/api/(.*)"
          pathType: ImplementationSpecific
          backend:
            service:
              name: {{ .Release.Name }}
              port:
                name: api
        - path: "/(.*)"
          pathType: ImplementationSpecific
          backend:
            service:
              name: {{ .Release.Name }}
              port:
                name: web
