{{- if and .Values.auth.username .Values.auth.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
data:
  auth: {{ printf "%s:%s" .Values.auth.username .Values.auth.password | b64enc | quote }}
type: Opaque 
{{- end }}
