apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - port: 7860
      name: web
      targetPort: 7860
    - port: 5000
      name: api
      targetPort: 5000
