apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "matrix-hermes.fullname" . }}
  labels:
    {{- include "matrix-hermes.labels" . | nindent 4 }}
{{- if eq .Values.k8sApiAccess "none" }}
automountServiceAccountToken: false
{{- end }}
