apiVersion: v1
name: personal-monitoring
annotations:
  catalog.cattle.io/release-name: pmon
version: 0.0.16
appVersion: 0.0.4
description: Personal Monitoring v0.0.4
icon: file://charts/monitoring/logo.svg
keywords:
- Monitoring
- Personal
- Grafana
- Prometheus
- Metrics
home: https://cerit.io
sources:
- https://github.com/CERIT-SC/rancher-apps
maintainers:
- name: CERIT-SC
  email: root@cerit-sc.cz
engine: gotpl
type: application
dependencies:
  - name: monitoring-personal
    version: "0.0.14"
    repository: "https://cerit-sc.github.io/helm-charts"
