{{- if .Values.ingress.enabled }}
apiVersion: {{ template "wordpress.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ template "wordpress.fullname" . }}
  labels: {{- include "wordpress.labels" . | nindent 4 }}
  annotations: 
    {{- if .Values.ingress.certManager }}
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    {{- end }}
    {{- if .Values.ingress.annotations }}
    {{- include "wordpress.tplValue" (dict "value" .Values.ingress.annotations "context" $) | nindent 4 }}
    {{- end }}
    external-dns.alpha.kubernetes.io/target: {{ .Values.ingress.dnstarget }}
spec:
  tls:
{{- if eq .Values.ingress.defhostname true }}
    - hosts:
        - {{ .Release.Name }}-{{ .Release.Namespace }}.dyn.cerit-sc.cz
      secretName: {{ printf "%s-%s-dyn-cerit-sc-cz-tls" .Release.Name .Release.Namespace  }}
  rules:
  - host: {{ .Release.Name }}-{{ .Release.Namespace }}.dyn.cerit-sc.cz
{{- else }}
    - hosts:
        - {{ .Values.ingress.customhostname }}
      secretName: {{ printf "%s-tls" .Values.ingress.customhostname | replace "." "-"  }}
  rules:
  - host: {{ .Values.ingress.customhostname }}
{{- end }}
    http:
      paths:
        - path: /
          backend:
            serviceName: {{ template "wordpress.fullname" . }}
            servicePort: http
            backend:
              serviceName: {{ template "wordpress.fullname" $ }}
              servicePort: http
{{- end }}
