apiVersion: v1
name: ridom-typer
version: 0.4
appVersion: 11.0.1
description: Ridom Typer server and client
icon: file://charts/ridom-seqsphere/v0.2/logo.png
keywords:
- Ridom Typer
- DNA
- Genomics 
- applications
home: https://www.ridom.de/seqsphere/index.shtml
sources:
- https://github.com/CERIT-SC/rancher-apps
maintainers:
- name: CERIT-SC
  email: root@cerit-sc.cz
engine: gotpl
