apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: overleaf
  labels:
    app.kubernetes.io/name: overleaf
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: overleaf
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes: [Ingress]
  ingress:
    # Ingress controller (kube-system) -> application HTTP port
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: TCP
          port: 8080
        - protocol: TCP
          port: 8089
