desktop: "cerit.io/desktops/ubuntu-xfce:24.04-user"
mincpu: 1
maxcpu: 4
minram: 4096Mi
maxram: 16384Mi
defhostname: true
customhostname: ""
username: ""
password: ""
persistenthome: true
resolution: "1920x1080"
gpu: Whole
