apiVersion: v1
name: desktop-server
version: 0.1
appVersion: 0.1
description: GPU-accelerated streaming using WebRTC
icon: file://logo.png
keywords:
- Remote desktop
- Webrtc
- 3D Acceleration
- applications
home: https://cerit.io
sources:
- https://github.com/CERIT-SC/rancher-apps
maintainers:
- name: CERIT-SC
  email: root@cerit-sc.cz
engine: gotpl
