desktop: "cerit.io/desktops/xfce:v0.1"
mincpu: 1
maxcpu: 4
minram: 4096Mi
maxram: 16384Mi
defhostname: true
customhostname: ""
username: "user"
password: ""
persistenthome: true
resolution: "1920x1080"
