{{- if and .Values.storage.munistorage.enable (ne .Values.storage.munistorage.server "") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "storage.name" . }}
  labels:
    cerit-cifs-secret: "yes"
    storage: {{ .Values.storage.munistorage.server | regexFind "^[^/]*" }}
    share: {{ regexReplaceAll "^[^/]*/" .Values.storage.munistorage.server "" }}
data:
  mount_flags: {{ printf "username=%s,password=%s,uid=1000,gid=1000,nosetuids,vers=3.11,noserverino,domain=UCN" .Values.storage.munistorage.username .Values.storage.munistorage.password | b64enc | quote }}
type: Opaque
{{ end }}
