apiVersion: v1
annotations:
 catalog.cattle.io/featured: "1"
name: pycharm
version: 0.2
appVersion: 2024.3.5
description: Pycharm
icon: file://charts/pycharm/v0.2/logo.svg
keywords:
- Remote desktop
- Webrtc
- 3D Acceleration
- applications
- VNC
- Pycharm
home: https://cerit.io
sources:
- https://github.com/CERIT-SC/rancher-apps
maintainers:
- name: CERIT-SC
  email: root@cerit-sc.cz
engine: gotpl
