apiVersion: v1
name: vmd
version: 1.1
appVersion: 1.9.4.57
description: VMD 1.9.4
icon: file://charts/vmd/v1.1/logo.svg
keywords:
- Remote desktop
- VMD
- Webrtc
- 3D Acceleration
- applications
home: https://cerit.io
sources:
- https://github.com/CERIT-SC/rancher-apps
maintainers:
- name: CERIT-SC
  email: root@cerit-sc.cz
engine: gotpl
