apiVersion: v1
name: vmd
version: 1.9.4
appVersion: 1.9.4
description: VMD 1.9.4
icon: file://logo.svg
keywords:
- Remote desktop
- VMD
- Webrtc
- 3D Acceleration
- applications
home: https://cerit.io
sources:
- https://github.com/CERIT-SC/rancher-apps
maintainers:
- name: CERIT-SC
  email: root@cerit-sc.cz
engine: gotpl
