apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  serviceName: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Release.Name }}
{{- if eq .Values.image "R 3.6.3/Debian 10" }}
        image: cerit.io/desktops/rstudio:v0.2 
{{- end }}
{{- if eq .Values.image "R 4.0.5/Ubuntu 20.04" }}
        image: cerit.io/desktops/rstudio:v4.0.5
{{- end }}
{{- if eq .Values.image "R 4.0.5/Ubuntu 20.04 Full" }}
        image: cerit.io/desktops/rstudio:v4.0.5-full
{{- end }}
        env:
        - name: PASSWORD
          valueFrom:
           secretKeyRef:
             key: password
             name: {{ .Release.Name }}-rstudiopassword
        securityContext:                                                          
          runAsUser: 1000 
          runAsGroup: 1000
        ports:
        - containerPort: 8787
        resources:
          limits:
            cpu: {{ .Values.maxcpu }}
            memory: {{ .Values.maxram }}
            ephemeral-storage: "10Gi"
          requests:
            cpu: {{ .Values.mincpu }}
            memory: {{ .Values.minram }}
        volumeMounts:
        - name: home
          mountPath: /home/rstudio
{{- if eq .Values.storage.enable true }}
        - name: data
          mountPath: /home/rstudio/data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: pvc-{{ include "storage.name" . }}
{{ end }}       
  volumeClaimTemplates:
  - metadata:
      name: home
    spec:
      accessModes: [ "ReadWriteMany" ]
      storageClassName: "nfs-csi"
      resources:
        requests:
          storage: 1Gi
