apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  serviceName: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      nodeSelector:
        storage: local-ssd
      initContainers:
      - name: init-{{ .Release.Name }}
        image: {{ .Values.image }}
        command: [ 'cp', '-rn', '/home/user/.', '/home/user2' ]
        securityContext:
          privileged: false
          runAsUser: 1000
          runAsGroup: 1000
        volumeMounts:
          - name: home
            mountPath: /home/user2
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.image }}
        securityContext:                                                          
          runAsUser: 1000 
          runAsGroup: 1000
        env:
        - name: PASSWORD
          valueFrom:
           secretKeyRef:
             key: auth
             name: terminal-{{ .Release.Name }}
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: {{ .Values.maxcpu }}
            memory: {{ .Values.maxram }}
          requests:
            cpu: {{ .Values.mincpu }}
            memory: {{ .Values.minram }}
        volumeMounts:
        - name: home
          mountPath: /home/user
        - name: data
          mountPath: /mnt
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: pvc-storage-elixir1-cerit-sc-cz
  volumeClaimTemplates:
  - metadata:
      name: home
    spec:
      accessModes: [ "ReadWriteMany" ]
      storageClassName: "nfs-csi"
      resources:
        requests:
          storage: 1Gi
