apiVersion: v1
kind: Secret
metadata:
  name: terminal-{{ .Release.Name }}
type: Opaque
data:
   auth: {{ .Values.password | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-storage-elixir1-cerit-sc-cz
  labels:
    cerit-cifs-secret: "yes"
  annotations:
    cerit.io/storage: "storage-elixir1.cerit-sc.cz"
    cerit.io/share: "lamb"
data:
  mount_flags: {{ printf "username=%d,password=%s,uid=1000,gid=1000,nosetuids,vers=3.11,noserverino,domain=UCN" .Values.storageusername .Values.storagepassword | b64enc | quote }}
type: Opaque

