apiVersion: v1
kind: Secret
metadata:
  name: terminal-{{ .Release.Name }}
type: Opaque
data:
   auth: {{ htpasswd .Values.username .Values.password | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: bioda-storage-elixir1-cerit-sc-cz
  labels:
    cerit-cifs-secret: "yes"
  annotations:
    cerit.io/storage: "storage-elixir1.cerit-sc.cz"
    cerit.io/share: "lambs"
data:
  mount_flags: {{ printf "username=%s,password=%s,uid=1000,gid=1000,nosetuids,vers=3.11,noserverino" .Values.storageusername .Values.storagepassword | b64enc | quote }}
type: Opaque

