annotations:
  catalog.cattle.io/release-name: phpmyadmin
apiVersion: v2
appVersion: 5.2.0
dependencies:
  - condition: db.bundleTestDB
    name: mariadb
    repository: https://charts.bitnami.com/bitnami
    tags:
      - phpmyadmin-database
    version: 11.x.x
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
description: phpMyAdmin client
engine: gotpl
home: https://github.com/bitnami/charts/tree/master/bitnami/phpmyadmin
icon: https://bitnami.com/assets/stacks/phpmyadmin/img/phpmyadmin-stack-220x234.png
keywords:
  - mariadb
  - mysql
  - phpmyadmin
  - storage
maintainers:
  - name: Bitnami
    url: https://github.com/bitnami/charts
name: phpmyadmin
sources:
  - https://github.com/bitnami/containers/tree/main/bitnami/phpmyadmin
  - https://www.phpmyadmin.net/
version: 10.2.4
