apiVersion: v1
kind: Service
metadata:
  name: {{ include "orthovenn.db.serviceName" . }}
  labels:
    {{- include "orthovenn.labels" . | nindent 4 }}
    app.kubernetes.io/component: db
  {{- with .Values.service.db.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.db.type }}
  selector:
    {{- include "orthovenn.selectorLabels" . | nindent 4 }}
  ports:
    - name: db
      port: {{ .Values.service.db.port }}
      targetPort: mysql
      protocol: TCP
