apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-web" (include "orthovenn.fullname" .) }}
  labels:
    {{- include "orthovenn.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
  {{- with .Values.service.web.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.web.type }}
  selector:
    {{- include "orthovenn.selectorLabels" . | nindent 4 }}
  ports:
    - name: web
      port: {{ .Values.service.web.port }}
      targetPort: web
      protocol: TCP
