apiVersion: kubeflow.org/v2beta1
kind: MPIJob
metadata:
  name: {{ .Release.Name }}
spec:
  slotsPerWorker: 1
  runPolicy:
    cleanPodPolicy: All
    ttlSecondsAfterFinished: 60
  sshAuthMountPath: {{ .Values.sshpath }}
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        metadata:
          labels: 
            io.cattle.field/appId: {{ .Release.Name }}
{{- if .Values.storage }}
        volumes:
        - name: vol1
          persistentVolumeClaim:
            claimName: pvc-{{ .Release.Name }}
{{- end }}
        spec:
          containers:
          - image: {{ .Values.image }}
            name: {{ .Release.Name }}-launcher
            securityContext:
              runAsUser: 1000
{{- if .Values.storage }}
            volumeMounts:
            - name: vol1
              mountPath: {{ .Values.storagemnt }}
{{- end }}
{{- if .Values.infiniband }}
            command: [ 'mpirun', '-mca', 'btl', 'openib,self', '-n', {{ .Values.workers | quote }}, {{ .Values.command | quote }} ]
{{- else }}
            command: [ 'mpirun', '-n', {{ .Values.workers | quote }}, {{ .Values.command | quote }} ]
{{- end }}
            resources:
              limits:
                cpu: 1
                memory: 1Gi
{{- if .Values.infiniband }}
                rdma/hca: 1
{{- end }}
    Worker:
      replicas: {{ .Values.workers }}
      template:
        metadata:
          labels:
            io.cattle.field/appId: {{ .Release.Name }}
{{- if .Values.storage }}
        volumes:
        - name: vol1
          persistentVolumeClaim:
            claimName: pvc-{{ .Release.Name }}
{{- end }}
        spec:
          containers:
          - image: {{ .Values.image }}
            name: {{ .Release.Name }}-worker
            securityContext:
              runAsUser: 1000
{{- if .Values.storage }}
            volumeMounts:
            - name: vol1
              mountPath: {{ .Values.storagemnt }}
{{- end }}
            resources:
              limits:
                cpu: {{ .Values.cpu }}
                memory: {{ .Values.memory }}
{{- if .Values.infiniband }}
                rdma/hca: 1
{{- end }}
