{{- if .Values.storage }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-{{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: nfs-csi
{{- end }}
