apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.image }}
        imagePullPolicy: IfNotPresent
        securityContext:                                                          
          runAsUser: 1000 
          runAsGroup: 1000
        env:
        - name: VNCPASSWORD
          valueFrom:
           secretKeyRef:
             key: password
             name: {{ .Release.Name }}-vnc
        - name: CONTAINER_TIMEZONE
          value: {{ .Values.timezone }}
        ports:
        - containerPort: 5901
        resources:
          requests:
            cpu: {{ .Values.mincpu }}
            memory: {{ .Values.minram }}
          limits:
            cpu: {{ .Values.maxcpu }}
            memory: {{ .Values.maxram }}
            ephemeral-storage: {{ .Values.ephem }}
        volumeMounts:
        - name: storagedata
          mountPath: /home/knimeuser/knime-workspace
        - name: dshm
          mountPath: /dev/shm
      volumes:
      - name: storagedata
        persistentVolumeClaim:
          claimName: pvc-{{ .Release.Namespace }}-{{ .Release.Name }}-storage-{{ printf "%s" .Values.storageserver | replace "," "-" }}  
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: {{ .Values.shm }}
