apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-minioauth
type: Opaque
data: 
   password: {{ .Values.password | b64enc | quote }}
   username: {{ .Values.username | b64enc | quote }}
