apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
type: Opaque
data: 
   auth: {{ printf "%s/%s" .Values.username .Values.password | b64enc | quote }}
---
{{- if .Values.webauth }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-web
type: Opaque
data:
   auth: {{ htpasswd .Values.webusername .Values.webpassword | b64enc | quote }}
{{- end }}
