apiVersion: v1
name: matrix-hermes
version: 0.2
appVersion: v0.21.1
description: Personal Matrix Agent
icon: file://charts/matrix-hermes/v0.1/logo.jpg
keywords:
- Matrix
- Element
- Hermes
sources:
- https://github.com/CERIT-SC/rancher-apps
maintainers:
- name: CERIT-SC
  email: root@cerit-sc.cz
engine: gotpl
