apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  annotations:
    kubernetes.io/ingress.class: nginx
    external-dns.alpha.kubernetes.io/target: {{ .Values.dnstarget }}
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
{{- if eq .Values.defhostname true }}
    - hosts: 
        - {{ .Release.Name }}-{{ .Release.Namespace }}.dyn.cerit-sc.cz 
      secretName: {{ printf "%s-%s-dyn-cerit-sc-cz-tls" .Release.Name .Release.Namespace  }}
  rules:
  - host: {{ .Release.Name }}-{{ .Release.Namespace }}.dyn.cerit-sc.cz
{{- else }}
    - hosts:
        - {{ .Values.customhostname }}
      secretName: {{ printf "%s-tls" .Values.customhostname | replace "." "-"  }}
  rules:
  - host: {{ .Values.customhostname }}
{{- end }}
    http:
      paths:
      - backend:
          service: 
            name: {{ .Release.Name }}
            port:
              number: 8787
        pathType: ImplementationSpecific

