{{- if .Values.mariadb.backup }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: mariadb-backup
spec:
  schedule: {{ .Values.mariadb.schedule }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 300
      template:
        spec:
          volumes:
            - name: database-backup
              persistentVolumeClaim:
                claimName: {{ .Values.mariadb.backupClaimName }}
          containers:
            - name: database-backup
              image: 'registry.access.redhat.com/rhscl/mariadb-101-rhel7:10.1'
              command:
                - 'bash'
                - '-eo'
                - 'pipefail'
                - '-c'
                - > 
                  trap "echo Backup failed; exit 0" ERR; 
                  FILENAME=backup-${DATABASE_NAME}-`date +%Y-%m-%d_%H%M%S`.sql.gz;
                  time (find /database-backup -type f -name "backup-${DATABASE_NAME}-*"  -exec ls -1tr "{}" + | head -n -${DATABASE_BACKUP_KEEP} | xargs rm -fr; 
                  mysqldump -u"${DATABASE_USER}" -p"${DATABASE_PASSWORD}" -h"${DATABASE_HOST}" -P"${DATABASE_PORT}" --skip-lock-tables --quick --add-drop-database --routines "${DATABASE_NAME}" | gzip > /database-backup/$FILENAME); 
                  echo "";
                  echo "Backup successful"; du -h /database-backup/$FILENAME; 
                  echo "to restore the backup to the serviced host use: $ mysql -u$DATABASE_USER -p<redacted> -h$DATABASE_HOST < /database-backup/<backupfile> (unpacked)"
              env:
                - name: DATABASE_USER
                  value: {{ .Values.mariadb.auth.username | quote }}
                - name: DATABASE_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: my-release-mariadb
                      key: mariadb-password
                - name: TZ
                  value: Europe/Zurich
                - name: DATABASE_BACKUP_KEEP
                  value: {{ .Values.mariadb.backupkeep | quote }}
                - name: DATABASE_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: my-release-mariadb
                      key: mariadb-root-password
                - name: DATABASE_HOST
                  value: {{.Release.Name }}-mariadb
                - name: DATABASE_PORT
                  value: "3306"
                - name: DATABASE_NAME
                  value: {{ .Values.mariadb.auth.database }}
                  
              volumeMounts:
                - name: database-backup
                  mountPath: /database-backup
          restartPolicy: Never
{{- end}}
