{{- if and .Values.externalDatabase.user .Values.externalDatabase.password }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: external-db-secret
data:
  username: {{ .Values.externalDatabase.user | b64enc | quote }}
  password: {{ .Values.externalDatabase.password | b64enc | quote }}
{{- end }}
